### ISSUE TITLE
Modernize Trash Hauler Schedule Lookup Tool

### ISSUE THREAD

**Issue by JordanPisani** [Commbocc/hc-trash-hauler-schedule-lookup#23]
- [x] use Vite
- [x] resizable iframe
- [x] [Dependent on Vue 2 component library](https://github.com/Commbocc/hcflgov-vue-esri-search/issues/3).
- [x] [CI/CD GitHub Action](https://github.com/Commbocc/hc-pet-tag-lookup/blob/main/.github/workflows/build-and-deploy.yml)
- [x] Create a fork and setup github pages for testing, PR any changes into vue-3 branch
- [x] update README with instructions on how to update [providers](https://airtable.com/appQrDnZGUnnURpdH/tblmpa77mYsu4vCiw/viwbA8Hb0K4DZQxWB?blocks=hide) (airtable)
- [x] Rather than skip holidays altogether, add them to an array of dates and show them as crossed out
- [x] after successful PR merge, [change](https://github.com/Commbocc/hc-trash-hauler-schedule-lookup/settings/branches) `main` to default branch, [delete](https://github.com/Commbocc/hc-trash-hauler-schedule-lookup/branches) `master` branch
- [x] close unnecessary dependabot PRs

RE: https://www.hillsboroughcounty.org/en/residents/property-owners-and-renters/trash-and-recycling/find-my-trash-collector-and-collection-schedule

**Comment by mccarthyk** [comment]
- [x] non-public solid waste provider

The returned provider will always show "Hillsborough County Solid Waste" to the public, however the customer service reps have requested a way of seeing which hauler is actually assigned.

**Comment by JordanPisani** [comment]
https://jordanpisani.github.io/hc-trash-hauler-schedule-lookup/

**Comment by JordanPisani** [comment]
https://github.com/Commbocc/hc-trash-hauler-schedule-lookup/pull/24
